version: "3"
services: 
  
  ms-clone:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "yarn start"
    ports: 
      - "80:3000"
    volumes: 
      - type: volume
        target: /home/node/app/.next