name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 5a441b22-a5b4-485a-ae31-76f2fb574fb3
          heroku_app_name: "try-ms-clone"
          heroku_email: "eko.nr@yahoo.com"
          usedocker: true
        env:
          NODE_ENV: production
